frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\Lists;
use common\models\User;
use frontend\models\Cards;
use frontend\models\Comments;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\Response;
use yii\helpers\Json;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'signup', 'index', 'logout', 'account'],
                'rules' => [
                    [
                        'actions' => ['login', 'signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index', 'logout', 'account', 'login', 'signup'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        Yii::$app->name = "Projek";
        return $this->render('index');
    }

    public function actionAccount()
    {
        Yii::$app->name = "Akun";
        $user = User::findIdentity(Yii::$app->user->identity->id);
        return $this->render('account', ['user' => $user]);
    }

    public function actionLogin()
    {
        $this->layout = "auth";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = "auth";
        $model = new SignupForm();
        $loginModel = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->addFlash("info", "Akun Telah Dibuat, Silahkan Masuk");
            return $this->redirect("login");
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/layouts/_alert.php
<div class="alert alert-success " id="alert-message">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <div id="message">Loading...</div>
</div>

frontend/views/layouts/_breadcrumb.php
<?php 

use yii\widgets\Breadcrumbs;

?>

<?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

frontend/views/layouts/_footer.php
<?php
use yii\helpers\Html;


?>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>
    </div>
</footer>

frontend/views/layouts/_header.php
<?php
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$url = explode("/", Yii::$app->request->url);
$mainUrl = "/" . $url[1];
$domain = $mainUrl;

    NavBar::begin([
        'brandLabel' => '<i class="fas fa-mug-hot"></i>&nbsp;&nbsp;App',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'shadow navbar-expand-lg navbar-light bg-light sticky-top'
        ],
    ]);
    ?>
    <?php if (!Yii::$app->user->isGuest) : ?>
        <?php if ((Yii::$app->request->url == $domain . "/") || (Yii::$app->request->url == $domain . "/site/index") || (Yii::$app->request->url == $domain . "/site/") || (Yii::$app->request->url == $domain . "/site") || (Yii::$app->request->url == $domain . "/site/index/")) : ?>
                <form onsubmit="searchProjects(event)" style="width:30%" class="mb-3 mt-3">
                    <div class="position-relative" data-placement="bottom" id="searchProjects" data-toggle="popover" data-html="true" data-content="">
                        <abbr title="Cari Projek">
                            <button type="submit" class="btn btn-dark position-absolute" style="right:0"><i class="fas fa-search"></i></button>
                        </abbr>
                        <input type="text" autocomplete="off" placeholder="Cari Projek" class="form-control" id="search" list="projects">
                    </div>
                    <datalist id="projects"></datalist>
                </form>
        <?php endif; ?>
    <?php endif; ?>

    <?php
    
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => '<i class="fas fa-user"></i>&nbsp;&nbsp;Daftar', 'url' => ['/site/signup']];
        $menuItems[] = ['label' => '<i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Masuk', 'url' => ['/site/login']];
    } else {
        $menuItems[] = ['label' => '<i class="fas fa-clipboard-list"></i>&nbsp;&nbsp;Projek', 'url' => ['/site/index']];
        $menuItems[] = ['label' => '<i class="fas fa-tools"></i>&nbsp;&nbsp;Akun', 'url' => ['/site/account']];

        $menuItems[] = [
            'label' => '<i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Keluar ('.Yii::$app->user->identity->username.')',
            'url' => ['/site/logout'],
            'linkOptions' => [
                'data-method' => 'post'
            ],
        ];

        

    }
    
    echo Nav::widget([
        'options' => ['class' => 'nav-pills nav-fill ml-auto'], 
        'items' => $menuItems,
        'encodeLabels' => false,
    ]);

    ?>

    <?php
        NavBar::end();
    ?>

frontend/views/layouts/auth.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

$url = explode("/", Yii::$app->request->url);
$path = Yii::$app->request->url;
$mainUrl = "/" . $url[1];

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?= $mainUrl; ?>/favicon.ico" sizes="16x16" type="image/png">
    <script type="text/javascript">
        var domain = "<?= $mainUrl; ?>" || "";
        var path = "<?= $path; ?>" || "";
    </script>
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    
    <?= $this->render("_header.php"); ?>
    <div class="position-fixed bg-light top-0 w-100 h-100" style="background-image: url(<?=$mainUrl;?>/img/wallpaper.png);background-size: 100%; background-repeat: no-repeat;"></div>
    <br>
    <div class="container">
        
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/blank.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    
<?= $content ?>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

frontend/views/layouts/main.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use common\widgets\Alert;

AppAsset::register($this);

$url = explode("/", Yii::$app->request->url);
$path = Yii::$app->request->url;
$mainUrl = "/" . $url[1];

?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?= $mainUrl; ?>/favicon.ico" sizes="16x16" type="image/png">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?= Html::csrfMetaTags() ?>
    <?php $this->head() ?>
    <script type="text/javascript">
        var domain = "<?= $mainUrl; ?>" || "";
        var path = "<?= $path; ?>" || "";
    </script>
</head>
<body style="background-color:#E5E7EB">

<?php $this->beginBody() ?>

    <?= $this->render("_header.php"); ?>
<div class="position-fixed bg-light top-0 w-100 h-100" style="background-image: url(<?=$mainUrl;?>/img/wallpaper.png);background-size: 100%; background-repeat: no-repeat;"></div>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $this->render("_alert.php"); ?>

        <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>